/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Characters
*
* Wrapping sgCharacters.pas
*/

#include <stdbool.h>
#include <stdint.h>

#ifndef sgCharacters
#define sgCharacters
#include "Types.h"

direction_angles character_angle_at(character c, int32_t index);
int32_t character_angle_max_at(character c, int32_t index);
int32_t character_angle_min_at(character c, int32_t index);
int32_t character_angles_length(character c);
void character_character_name(character c, char *result);
int32_t character_current_direction(character c);
int32_t character_current_state(character c);
int32_t character_direction_count(character c);
void character_directions(character c, string_array result, int32_t result_len);
void character_filename(character c, char *result);
void character_name(character c, char *result);
character character_named(const char *name);
void character_set_current_direction(character c, int32_t direction);
void character_set_current_state(character c, int32_t state);
void character_set_name(character c, const char *name);
void character_set_type(character c, const char *name);
void character_set_value(character c, int32_t idx, float val);
void character_set_value_by_name(character c, const char *name, float val);
bool character_shown_layers_at(character c, int32_t index);
sprite character_sprite(character c);
int32_t character_state_count(character c);
void character_states(character c, string_array result, int32_t result_len);
void character_type(character c, char *result);
float character_value_at(character c, int32_t index);
int32_t character_value_count(character c);
void character_value_names(character c, string_array result, int32_t result_len);
void draw_character(character c);
void draw_character_sprite(character c);
void draw_character_with_stationary(character c, int32_t stationaryState, int32_t state);
void free_character(character *c);
bool has_character(const char *name);
character load_character(const char *filename);
character load_character_named(const char *name, const char *filename);
void release_all_characters();
void release_character(const char *name);
void set_active_layer(character c);
void toggle_layer_visibility(character c, int32_t index);
bool update_direction_animation(character c);
bool update_direction_animation_with_stationary(character c, int32_t state, int32_t newState);
#endif

