/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Text
*
* Wrapping sgText.pas
*/

#include <stdbool.h>
#include <stdint.h>

#ifndef sgText
#define sgText
#include "Types.h"

void draw_framerate_with_simple_font(int32_t x, int32_t y);
void draw_framerate(int32_t x, int32_t y, font font);
void draw_framerate_font_named(int32_t x, int32_t y, const char *name);
void draw_framerate_font_named_size(int32_t x, int32_t y, const char *name, int32_t size);
void draw_simple_text_pt(const char *theText, color textColor, const point2d *pt);
void draw_simple_text_pt_byval(const char *theText, color textColor, const point2d pt);
void draw_text_at_point(const char *theText, color textColor, font theFont, const point2d *pt);
void draw_text_at_point_byval(const char *theText, color textColor, font theFont, const point2d pt);
void draw_simple_text(const char *theText, color textColor, float x, float y);
void draw_text_at_point_with_font_named(const char *theText, color textColor, const char *name, const point2d *pt);
void draw_text_at_point_with_font_named_byval(const char *theText, color textColor, const char *name, const point2d pt);
void draw_text_on_bitmap_at_point_with_font_named(bitmap dest, const char *theText, color textColor, const char *name, const point2d *pt);
void draw_text_on_bitmap_at_point_with_font_named_byval(bitmap dest, const char *theText, color textColor, const char *name, const point2d pt);
void draw_text(const char *theText, color textColor, font theFont, float x, float y);
void draw_text_with_font_named(const char *theText, color textColor, const char *name, float x, float y);
void draw_simple_text_on_bitmap(bitmap dest, const char *theText, color textColor, float x, float y);
void draw_text_on_bitmap_at_point(bitmap dest, const char *theText, color textColor, font theFont, const point2d *pt);
void draw_text_on_bitmap_at_point_byval(bitmap dest, const char *theText, color textColor, font theFont, const point2d pt);
void draw_text_at_point_with_font_named_and_size(const char *theText, color textColor, const char *name, int32_t size, const point2d *pt);
void draw_text_at_point_with_font_named_and_size_byval(const char *theText, color textColor, const char *name, int32_t size, const point2d pt);
void draw_text_on_bitmap_at_point_with_font_named_and_size(bitmap dest, const char *theText, color textColor, const char *name, int32_t size, const point2d *pt);
void draw_text_on_bitmap_at_point_with_font_named_and_size_byval(bitmap dest, const char *theText, color textColor, const char *name, int32_t size, const point2d pt);
void draw_text_with_font_named_size(const char *theText, color textColor, const char *name, int32_t size, float x, float y);
void draw_text_on_bitmap(bitmap dest, const char *theText, color textColor, font theFont, int32_t x, int32_t y);
void draw_text_on_bitmap_with_font_named(bitmap dest, const char *theText, color textColor, const char *name, int32_t x, int32_t y);
void draw_text_on_bitmap_with_font_named_and_size(bitmap dest, const char *theText, color textColor, const char *name, int32_t size, int32_t x, int32_t y);
void draw_text_lines_with_font_named_and_size(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, float x, float y, int32_t w, int32_t h);
void draw_text_lines_on_bitmap_with_font_named(bitmap dest, const char *theText, color textColor, color backColor, const char *name, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_text_lines_on_bitmap(bitmap dest, const char *theText, color textColor, color backColor, font theFont, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_text_lines_on_bitmap_with_font_named_and_size(bitmap dest, const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_text_lines_in_rect_with_font_named(const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_with_font_named_byval(const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect(const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_byval(const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_on_bitmap(bitmap dest, const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_bitmap_byval(bitmap dest, const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_on_bitmap_with_font_named(bitmap dest, const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_bitmap_with_font_named_byval(bitmap dest, const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_with_font_named_and_size(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_with_font_named_and_size_byval(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_on_bitmap_with_font_named_and_size(bitmap dest, const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_bitmap_with_font_named_and_size_byval(bitmap dest, const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle withinRect);
void draw_text_lines(const char *theText, color textColor, color backColor, font theFont, font_alignment align, float x, float y, int32_t w, int32_t h);
void draw_text_lines_with_font_named(const char *theText, color textColor, color backColor, const char *name, font_alignment align, float x, float y, int32_t w, int32_t h);
void draw_text_lines_on_screen_with_font_named_with_size(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_text_lines_in_rect_on_screen(const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_screen_byval(const char *theText, color textColor, color backColor, font theFont, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_on_screen_with_font_named(const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_screen_with_font_named_byval(const char *theText, color textColor, color backColor, const char *name, font_alignment align, const rectangle withinRect);
void draw_text_lines_in_rect_on_screen_with_font_named_and_size(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle *withinRect);
void draw_text_lines_in_rect_on_screen_with_font_named_and_size_byval(const char *theText, color textColor, color backColor, const char *name, int32_t size, font_alignment align, const rectangle withinRect);
void draw_text_lines_on_screen(const char *theText, color textColor, color backColor, font theFont, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_text_lines_on_screen_with_font_named(const char *theText, color textColor, color backColor, const char *name, font_alignment align, int32_t x, int32_t y, int32_t w, int32_t h);
void draw_simple_text_on_screen(const char *theText, color textColor, float x, float y);
void draw_text_on_screen_at_point_with_font_named(const char *theText, color textColor, const char *name, const point2d *pt);
void draw_text_on_screen_at_point_with_font_named_byval(const char *theText, color textColor, const char *name, const point2d pt);
void draw_text_on_screen_at_point(const char *theText, color textColor, font theFont, const point2d *pt);
void draw_text_on_screen_at_point_byval(const char *theText, color textColor, font theFont, const point2d pt);
void draw_text_on_screen(const char *theText, color textColor, font theFont, int32_t x, int32_t y);
void draw_text_on_screen_with_font_named(const char *theText, color textColor, const char *name, int32_t x, int32_t y);
void draw_text_on_screen_at_point_with_font_named_and_size(const char *theText, color textColor, const char *name, int32_t size, const point2d *pt);
void draw_text_on_screen_at_point_with_font_named_and_size_byval(const char *theText, color textColor, const char *name, int32_t size, const point2d pt);
void draw_text_on_screen_with_font_named_and_size(const char *theText, color textColor, const char *name, int32_t size, int32_t x, int32_t y);
font_style font_font_style(font font);
void font_name_for(const char *fontName, int32_t size, char *result);
font font_named(const char *name);
font font_named_with_size(const char *name, int32_t size);
void font_set_style(font font, font_style value);
void free_font(font *fontToFree);
bool has_font(const char *name);
font load_font(const char *fontName, int32_t size);
font load_font_named(const char *name, const char *filename, int32_t size);
void release_all_fonts();
void release_font(const char *name);
font_alignment text_alignment_from(const char *str);
int32_t text_height(font theFont, const char *theText);
int32_t text_width(font theFont, const char *theText);
#endif

