/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Animations
*
* Wrapping sgAnimations.pas
*/

#include "SGSDK.h"
#include "Animations.h"

#include "Types.h"

int32_t animation_current_cell(animation anim)
{
    return sg_Animations_AnimationCurrentCell(anim);
}

bool animation_ended(animation anim)
{
    return sg_Animations_AnimationEnded(anim) != 0;
}

bool animation_entered_frame(animation anim)
{
    return sg_Animations_AnimationEnteredFrame(anim) != 0;
}

float animation_frame_time(animation anim)
{
    return sg_Animations_AnimationFrameTime(anim);
}

int32_t animation_index(animation_script temp, const char *name)
{
    return sg_Animations_AnimationIndex(temp, name);
}

void animation_name(animation_script temp, int32_t idx, char *result)
{
    sg_Animations_AnimationName(temp, idx, result);
}

animation_script animation_script_named(const char *name)
{
    return sg_Animations_AnimationScriptNamed(name);
}

void assign_animation_named(animation anim, const char *name, animation_script frames)
{
    sg_Animations_AssignAnimationNamed(anim, name, frames);
}

void assign_animation(animation anim, int32_t idx, animation_script frames)
{
    sg_Animations_AssignAnimation(anim, idx, frames);
}

void assign_animation_named_with_sound(animation anim, const char *name, animation_script frames, bool withSound)
{
    sg_Animations_AssignAnimationNamedWithSound(anim, name, frames, withSound != 0);
}

void assign_animation_with_sound(animation anim, int32_t idx, animation_script frames, bool withSound)
{
    sg_Animations_AssignAnimationWithSound(anim, idx, frames, withSound != 0);
}

animation create_animation_with_sound(int32_t identifier, animation_script frames)
{
    return sg_Animations_CreateAnimationWithSound(identifier, frames);
}

animation create_animation_named(const char *identifier, animation_script frames)
{
    return sg_Animations_CreateAnimationNamed(identifier, frames);
}

animation create_animation(int32_t identifier, animation_script frames, bool withSound)
{
    return sg_Animations_CreateAnimation(identifier, frames, withSound != 0);
}

animation create_animation_named_with_sound(const char *identifier, animation_script frames, bool withSound)
{
    return sg_Animations_CreateAnimationNamedWithSound(identifier, frames, withSound != 0);
}

void draw_animation_at_point(animation ani, bitmap bmp, const point2d *pt)
{
    sg_Animations_DrawAnimationAtPoint(ani, bmp, pt);
}

void draw_animation_at_point_byval(animation ani, bitmap bmp, const point2d pt)
{
    sg_Animations_DrawAnimationAtPoint(ani, bmp, &pt);
}

void draw_animation(animation ani, bitmap bmp, int32_t x, int32_t y)
{
    sg_Animations_DrawAnimation(ani, bmp, x, y);
}

void draw_animation_onto_dest_at_pt(bitmap dest, animation ani, bitmap bmp, const point2d *pt)
{
    sg_Animations_DrawAnimationOntoDestAtPt(dest, ani, bmp, pt);
}

void draw_animation_onto_dest_at_pt_byval(bitmap dest, animation ani, bitmap bmp, const point2d pt)
{
    sg_Animations_DrawAnimationOntoDestAtPt(dest, ani, bmp, &pt);
}

void draw_animation_onto_dest(bitmap dest, animation ani, bitmap bmp, int32_t x, int32_t y)
{
    sg_Animations_DrawAnimationOntoDest(dest, ani, bmp, x, y);
}

void draw_animation_on_screen_at_pt(animation ani, bitmap bmp, const point2d *pt)
{
    sg_Animations_DrawAnimationOnScreenAtPt(ani, bmp, pt);
}

void draw_animation_on_screen_at_pt_byval(animation ani, bitmap bmp, const point2d pt)
{
    sg_Animations_DrawAnimationOnScreenAtPt(ani, bmp, &pt);
}

void draw_animation_on_screen(animation ani, bitmap bmp, int32_t x, int32_t y)
{
    sg_Animations_DrawAnimationOnScreen(ani, bmp, x, y);
}

void free_animation(animation *ani)
{
    sg_Animations_FreeAnimation(ani);
}

void free_animation_script(animation_script *framesToFree)
{
    sg_Animations_FreeAnimationScript(framesToFree);
}

bool has_animation_script(const char *name)
{
    return sg_Animations_HasAnimationScript(name) != 0;
}

animation_script load_animation_script(const char *filename)
{
    return sg_Animations_LoadAnimationScript(filename);
}

animation_script load_animation_script_named(const char *name, const char *filename)
{
    return sg_Animations_LoadAnimationScriptNamed(name, filename);
}

void release_all_animation_scripts()
{
    sg_Animations_ReleaseAllAnimationScripts();
}

void release_animation_script(const char *name)
{
    sg_Animations_ReleaseAnimationScript(name);
}

void restart_animation(animation anim)
{
    sg_Animations_RestartAnimation(anim);
}

void reset_animation_with_sound(animation anim, bool withSound)
{
    sg_Animations_ResetAnimationWithSound(anim, withSound != 0);
}

void update_animation(animation anim)
{
    sg_Animations_UpdateAnimation(anim);
}

void update_animation_pct(animation anim, float pct)
{
    sg_Animations_UpdateAnimationPct(anim, pct);
}

void update_animation_pct_and_sound(animation anim, float pct, bool withSound)
{
    sg_Animations_UpdateAnimationPctAndSound(anim, pct, withSound != 0);
}

