/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Images
*
* Wrapping sgImages.pas
*/

#include "SGSDK.h"
#include "Images.h"

#include "Types.h"

circle bitmap_cell_circle(bitmap bmp, const point2d *pt)
{
    return sg_Images_BitmapCellCircle(bmp, pt);
}

circle bitmap_cell_circle_byval(bitmap bmp, const point2d pt)
{
    return sg_Images_BitmapCellCircle(bmp, &pt);
}

circle bitmap_cell_circle_xy(bitmap bmp, int32_t x, int32_t y)
{
    return sg_Images_BitmapCellCircleXY(bmp, x, y);
}

int32_t bitmap_cell_columns(bitmap bmp)
{
    return sg_Images_BitmapCellColumns(bmp);
}

int32_t bitmap_cell_count(bitmap bmp)
{
    return sg_Images_BitmapCellCount(bmp);
}

int32_t bitmap_cell_height(bitmap bmp)
{
    return sg_Images_BitmapCellHeight(bmp);
}

bitmap_cell bitmap_cell_of(bitmap bmp, int32_t cell)
{
    return sg_Images_BitmapCellOf(bmp, cell);
}

rectangle bitmap_cell_rectangle_at_origin(bitmap bmp)
{
    return sg_Images_BitmapCellRectangleAtOrigin(bmp);
}

rectangle bitmap_cell_rectangle(const point2d *pt, bitmap bmp)
{
    return sg_Images_BitmapCellRectangle(pt, bmp);
}

rectangle bitmap_cell_rectangle_byval(const point2d pt, bitmap bmp)
{
    return sg_Images_BitmapCellRectangle(&pt, bmp);
}

rectangle bitmap_cell_rectangle_xy(float x, float y, bitmap bmp)
{
    return sg_Images_BitmapCellRectangleXY(x, y, bmp);
}

int32_t bitmap_cell_rows(bitmap bmp)
{
    return sg_Images_BitmapCellRows(bmp);
}

int32_t bitmap_cell_width(bitmap bmp)
{
    return sg_Images_BitmapCellWidth(bmp);
}

circle bitmap_circle(bitmap bmp, const point2d *pt)
{
    return sg_Images_BitmapCircle(bmp, pt);
}

circle bitmap_circle_byval(bitmap bmp, const point2d pt)
{
    return sg_Images_BitmapCircle(bmp, &pt);
}

circle bitmap_circle_xy(bitmap bmp, int32_t x, int32_t y)
{
    return sg_Images_BitmapCircleXY(bmp, x, y);
}

void bitmap_filename(bitmap bmp, char *result)
{
    sg_Images_BitmapFilename(bmp, result);
}

int32_t bitmap_height_for_cell(const bitmap_cell *bmp)
{
    return sg_Images_BitmapHeightForCell(bmp);
}

int32_t bitmap_height_for_cell_byval(const bitmap_cell bmp)
{
    return sg_Images_BitmapHeightForCell(&bmp);
}

int32_t bitmap_height(bitmap bmp)
{
    return sg_Images_BitmapHeight(bmp);
}

void bitmap_name(bitmap bmp, char *result)
{
    sg_Images_BitmapName(bmp, result);
}

bitmap bitmap_named(const char *name)
{
    return sg_Images_BitmapNamed(name);
}

rectangle bitmap_rect_at_origin(bitmap bmp)
{
    return sg_Images_BitmapRectAtOrigin(bmp);
}

rectangle bitmap_rect_xy(float x, float y, bitmap bmp)
{
    return sg_Images_BitmapRectXY(x, y, bmp);
}

rectangle bitmap_rectangle_of_cell(bitmap src, int32_t cell)
{
    return sg_Images_BitmapRectangleOfCell(src, cell);
}

void bitmap_set_cell_details(bitmap bmp, int32_t width, int32_t height, int32_t columns, int32_t rows, int32_t count)
{
    sg_Images_BitmapSetCellDetails(bmp, width, height, columns, rows, count);
}

int32_t bitmap_width(bitmap bmp)
{
    return sg_Images_BitmapWidth(bmp);
}

int32_t bitmap_width_for_cell(const bitmap_cell *bmp)
{
    return sg_Images_BitmapWidthForCell(bmp);
}

int32_t bitmap_width_for_cell_byval(const bitmap_cell bmp)
{
    return sg_Images_BitmapWidthForCell(&bmp);
}

bool bitmaps_interchangable(bitmap bmp1, bitmap bmp2)
{
    return sg_Images_BitmapsInterchangable(bmp1, bmp2) != 0;
}

void clear_surface_to_black(bitmap dest)
{
    sg_Images_ClearSurfaceToBlack(dest);
}

void clear_surface(bitmap dest, color toColor)
{
    sg_Images_ClearSurface(dest, toColor);
}

bitmap combine_into_grid(const bitmap *bitmaps, int32_t cols, int32_t bitmaps_len)
{
    return sg_Images_CombineIntoGrid(bitmaps, cols, bitmaps_len);
}

bitmap combine_into_grid_byval(const bitmap *bitmaps, int32_t cols, int32_t bitmaps_len)
{
    return sg_Images_CombineIntoGrid(bitmaps, cols, bitmaps_len);
}

bitmap create_bitmap(int32_t width, int32_t height)
{
    return sg_Images_CreateBitmap(width, height);
}

bitmap create_bitmap_named(const char *name, int32_t width, int32_t height)
{
    return sg_Images_CreateBitmapNamed(name, width, height);
}

void draw_bitmap(bitmap src, float x, float y)
{
    sg_Images_DrawBitmap(src, x, y);
}

void draw_bitmap_named(const char *name, float x, float y)
{
    sg_Images_DrawBitmapNamed(name, x, y);
}

void draw_bitmap_named_at_point(const char *name, const point2d *position)
{
    sg_Images_DrawBitmapNamedAtPoint(name, position);
}

void draw_bitmap_named_at_point_byval(const char *name, const point2d position)
{
    sg_Images_DrawBitmapNamedAtPoint(name, &position);
}

void draw_bitmap_at_point(bitmap src, const point2d *position)
{
    sg_Images_DrawBitmapAtPoint(src, position);
}

void draw_bitmap_at_point_byval(bitmap src, const point2d position)
{
    sg_Images_DrawBitmapAtPoint(src, &position);
}

void draw_bitmap_at_point_onto(bitmap dest, bitmap src, const point2d *position)
{
    sg_Images_DrawBitmapAtPointOnto(dest, src, position);
}

void draw_bitmap_at_point_onto_byval(bitmap dest, bitmap src, const point2d position)
{
    sg_Images_DrawBitmapAtPointOnto(dest, src, &position);
}

void draw_bitmap_onto(bitmap dest, bitmap src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapOnto(dest, src, x, y);
}

void draw_bitmap_cell_at_point(const bitmap_cell *src, const point2d *position)
{
    sg_Images_DrawBitmapCellAtPoint(src, position);
}

void draw_bitmap_cell_at_point_byval(const bitmap_cell src, const point2d position)
{
    sg_Images_DrawBitmapCellAtPoint(&src, &position);
}

void draw_bitmap_cell(const bitmap_cell *src, float x, float y)
{
    sg_Images_DrawBitmapCell(src, x, y);
}

void draw_bitmap_cell_byval(const bitmap_cell src, float x, float y)
{
    sg_Images_DrawBitmapCell(&src, x, y);
}

void draw_bitmap_cell_at_point_onto(bitmap dest, const bitmap_cell *src, const point2d *position)
{
    sg_Images_DrawBitmapCellAtPointOnto(dest, src, position);
}

void draw_bitmap_cell_at_point_onto_byval(bitmap dest, const bitmap_cell src, const point2d position)
{
    sg_Images_DrawBitmapCellAtPointOnto(dest, &src, &position);
}

void draw_bitmap_cell_onto(bitmap dest, const bitmap_cell *src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapCellOnto(dest, src, x, y);
}

void draw_bitmap_cell_onto_byval(bitmap dest, const bitmap_cell src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapCellOnto(dest, &src, x, y);
}

void draw_bitmap_cell_at_point_on_screen(const bitmap_cell *src, const point2d *position)
{
    sg_Images_DrawBitmapCellAtPointOnScreen(src, position);
}

void draw_bitmap_cell_at_point_on_screen_byval(const bitmap_cell src, const point2d position)
{
    sg_Images_DrawBitmapCellAtPointOnScreen(&src, &position);
}

void draw_bitmap_cell_on_screen(const bitmap_cell *src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapCellOnScreen(src, x, y);
}

void draw_bitmap_cell_on_screen_byval(const bitmap_cell src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapCellOnScreen(&src, x, y);
}

void draw_bitmap_at_point_on_screen(bitmap src, const point2d *position)
{
    sg_Images_DrawBitmapAtPointOnScreen(src, position);
}

void draw_bitmap_at_point_on_screen_byval(bitmap src, const point2d position)
{
    sg_Images_DrawBitmapAtPointOnScreen(src, &position);
}

void draw_bitmap_on_screen(bitmap src, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapOnScreen(src, x, y);
}

void draw_bitmap_part_from_rect_at_point(bitmap src, const rectangle *source, const point2d *position)
{
    sg_Images_DrawBitmapPartFromRectAtPoint(src, source, position);
}

void draw_bitmap_part_from_rect_at_point_byval(bitmap src, const rectangle source, const point2d position)
{
    sg_Images_DrawBitmapPartFromRectAtPoint(src, &source, &position);
}

void draw_bitmap_part_from_rect(bitmap src, const rectangle *source, float x, float y)
{
    sg_Images_DrawBitmapPartFromRect(src, source, x, y);
}

void draw_bitmap_part_from_rect_byval(bitmap src, const rectangle source, float x, float y)
{
    sg_Images_DrawBitmapPartFromRect(src, &source, x, y);
}

void draw_bitmap_part_from_rect_at_point_onto(bitmap dest, bitmap src, const rectangle *source, const point2d *position)
{
    sg_Images_DrawBitmapPartFromRectAtPointOnto(dest, src, source, position);
}

void draw_bitmap_part_from_rect_at_point_onto_byval(bitmap dest, bitmap src, const rectangle source, const point2d position)
{
    sg_Images_DrawBitmapPartFromRectAtPointOnto(dest, src, &source, &position);
}

void draw_bitmap_part_from_rect_onto(bitmap dest, bitmap src, const rectangle *source, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartFromRectOnto(dest, src, source, x, y);
}

void draw_bitmap_part_from_rect_onto_byval(bitmap dest, bitmap src, const rectangle source, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartFromRectOnto(dest, src, &source, x, y);
}

void draw_bitmap_part(bitmap src, int32_t srcX, int32_t srcY, int32_t srcW, int32_t srcH, float x, float y)
{
    sg_Images_DrawBitmapPart(src, srcX, srcY, srcW, srcH, x, y);
}

void draw_bitmap_part_onto(bitmap dest, bitmap src, int32_t srcX, int32_t srcY, int32_t srcW, int32_t srcH, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartOnto(dest, src, srcX, srcY, srcW, srcH, x, y);
}

void draw_bitmap_part_from_rect_at_point_on_screen(bitmap src, const rectangle *source, const point2d *position)
{
    sg_Images_DrawBitmapPartFromRectAtPointOnScreen(src, source, position);
}

void draw_bitmap_part_from_rect_at_point_on_screen_byval(bitmap src, const rectangle source, const point2d position)
{
    sg_Images_DrawBitmapPartFromRectAtPointOnScreen(src, &source, &position);
}

void draw_bitmap_part_from_rect_on_screen(bitmap src, const rectangle *source, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartFromRectOnScreen(src, source, x, y);
}

void draw_bitmap_part_from_rect_on_screen_byval(bitmap src, const rectangle source, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartFromRectOnScreen(src, &source, x, y);
}

void draw_bitmap_part_on_screen(bitmap src, int32_t srcX, int32_t srcY, int32_t srcW, int32_t srcH, int32_t x, int32_t y)
{
    sg_Images_DrawBitmapPartOnScreen(src, srcX, srcY, srcW, srcH, x, y);
}

void draw_cell(bitmap src, int32_t cell, const point2d *position)
{
    sg_Images_DrawCell(src, cell, position);
}

void draw_cell_byval(bitmap src, int32_t cell, const point2d position)
{
    sg_Images_DrawCell(src, cell, &position);
}

void draw_cell_onto(bitmap dest, bitmap src, int32_t cell, const point2d *position)
{
    sg_Images_DrawCellOnto(dest, src, cell, position);
}

void draw_cell_onto_byval(bitmap dest, bitmap src, int32_t cell, const point2d position)
{
    sg_Images_DrawCellOnto(dest, src, cell, &position);
}

void draw_cell_xy(bitmap src, int32_t cell, float x, float y)
{
    sg_Images_DrawCellXY(src, cell, x, y);
}

void draw_cell_onto_xy(bitmap dest, bitmap src, int32_t cell, float x, float y)
{
    sg_Images_DrawCellOntoXY(dest, src, cell, x, y);
}

void draw_cell_on_screen(bitmap src, int32_t cell, const point2d *position)
{
    sg_Images_DrawCellOnScreen(src, cell, position);
}

void draw_cell_on_screen_byval(bitmap src, int32_t cell, const point2d position)
{
    sg_Images_DrawCellOnScreen(src, cell, &position);
}

void draw_cell_on_screen_xy(bitmap src, int32_t cell, float x, float y)
{
    sg_Images_DrawCellOnScreenXY(src, cell, x, y);
}

void free_bitmap(bitmap *bitmapToFree)
{
    sg_Images_FreeBitmap(bitmapToFree);
}

bool has_bitmap(const char *name)
{
    return sg_Images_HasBitmap(name) != 0;
}

bitmap load_bitmap(const char *filename)
{
    return sg_Images_LoadBitmap(filename);
}

bitmap load_bitmap_with_transparent_color(const char *filename, bool transparent, color transparentColor)
{
    return sg_Images_LoadBitmapWithTransparentColor(filename, transparent != 0, transparentColor);
}

bitmap load_bitmap_named(const char *name, const char *filename)
{
    return sg_Images_LoadBitmapNamed(name, filename);
}

bitmap load_transparent_bitmap(const char *filename, color transparentColor)
{
    return sg_Images_LoadBitmapWithTransparentColor(filename, true != 0, transparentColor);
}

bitmap load_transparent_bitmap_named(const char *name, const char *filename, color transparentColor)
{
    return sg_Images_LoadTransparentBitmapNamed(name, filename, transparentColor);
}

void make_opaque(bitmap bmp)
{
    sg_Images_MakeOpaque(bmp);
}

void make_transparent(bitmap bmp)
{
    sg_Images_MakeTransparent(bmp);
}

void optimise_bitmap(bitmap surface)
{
    sg_Images_OptimiseBitmap(surface);
}

bool pixel_drawn_at_point(bitmap bmp, int32_t x, int32_t y)
{
    return sg_Images_PixelDrawnAtPoint(bmp, x, y) != 0;
}

void release_all_bitmaps()
{
    sg_Images_ReleaseAllBitmaps();
}

void release_bitmap(const char *name)
{
    sg_Images_ReleaseBitmap(name);
}

bitmap rotate_scale_bitmap(bitmap src, float degRot, float scale)
{
    return sg_Images_RotateScaleBitmap(src, degRot, scale);
}

bool same_bitmap_cell(const bitmap_cell *bmp1, const bitmap_cell *bmp2)
{
    return sg_Images_SameBitmapCell(bmp1, bmp2) != 0;
}

bool same_bitmap_cell_byval(const bitmap_cell bmp1, const bitmap_cell bmp2)
{
    return sg_Images_SameBitmapCell(&bmp1, &bmp2) != 0;
}

void save_bitmap(bitmap src, const char *filepath)
{
    sg_Images_SaveBitmap(src, filepath);
}

void save_to_png(bitmap bmp, const char *filename)
{
    sg_Images_SaveToPNG(bmp, filename);
}

void set_opacity(bitmap bmp, float pct)
{
    sg_Images_SetOpacity(bmp, pct);
}

void set_transparent_color(bitmap src, color clr)
{
    sg_Images_SetTransparentColor(src, clr);
}

void setup_bitmap_for_collisions(bitmap src)
{
    sg_Images_SetupBitmapForCollisions(src);
}

