/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Physics
*
* Wrapping sgPhysics.pas
*/

#include "SGSDK.h"
#include "Physics.h"

#include "Types.h"

bool bitmap_at_points_collision(bitmap bmp1, const point2d *pt1, bitmap bmp2, const point2d *pt2)
{
    return sg_Physics_BitmapAtPointsCollision(bmp1, pt1, bmp2, pt2) != 0;
}

bool bitmap_at_points_collision_byval(bitmap bmp1, const point2d pt1, bitmap bmp2, const point2d pt2)
{
    return sg_Physics_BitmapAtPointsCollision(bmp1, &pt1, bmp2, &pt2) != 0;
}

bool bitmap_collision(bitmap bmp1, int32_t x1, int32_t y1, bitmap bmp2, int32_t x2, int32_t y2)
{
    return sg_Physics_BitmapCollision(bmp1, x1, y1, bmp2, x2, y2) != 0;
}

bool bitmaps_parts_collision(bitmap bmp1, const point2d *pt1, const rectangle *part1, bitmap bmp2, const point2d *pt2, const rectangle *part2)
{
    return sg_Physics_BitmapsPartsCollision(bmp1, pt1, part1, bmp2, pt2, part2) != 0;
}

bool bitmaps_parts_collision_byval(bitmap bmp1, const point2d pt1, const rectangle part1, bitmap bmp2, const point2d pt2, const rectangle part2)
{
    return sg_Physics_BitmapsPartsCollision(bmp1, &pt1, &part1, bmp2, &pt2, &part2) != 0;
}

bool bitmap_part_point_xycollision(bitmap bmp, int32_t x, int32_t y, const rectangle *part, const point2d *pt)
{
    return sg_Physics_BitmapPartPointXYCollision(bmp, x, y, part, pt) != 0;
}

bool bitmap_part_point_xycollision_byval(bitmap bmp, int32_t x, int32_t y, const rectangle part, const point2d pt)
{
    return sg_Physics_BitmapPartPointXYCollision(bmp, x, y, &part, &pt) != 0;
}

bool bitmap_part_point_collision(bitmap bmp, int32_t x, int32_t y, const rectangle *part, float ptX, float ptY)
{
    return sg_Physics_BitmapPartPointCollision(bmp, x, y, part, ptX, ptY) != 0;
}

bool bitmap_part_point_collision_byval(bitmap bmp, int32_t x, int32_t y, const rectangle part, float ptX, float ptY)
{
    return sg_Physics_BitmapPartPointCollision(bmp, x, y, &part, ptX, ptY) != 0;
}

bool bitmap_point_pt_collision(bitmap bmp, int32_t x, int32_t y, const point2d *pt)
{
    return sg_Physics_BitmapPointPtCollision(bmp, x, y, pt) != 0;
}

bool bitmap_point_pt_collision_byval(bitmap bmp, int32_t x, int32_t y, const point2d pt)
{
    return sg_Physics_BitmapPointPtCollision(bmp, x, y, &pt) != 0;
}

bool bitmap_point_collision(bitmap bmp, int32_t x, int32_t y, float ptX, float ptY)
{
    return sg_Physics_BitmapPointCollision(bmp, x, y, ptX, ptY) != 0;
}

bool bitmap_part_at_pt_rect_collision(bitmap bmp, const point2d *pt, const rectangle *part, const rectangle *rect)
{
    return sg_Physics_BitmapPartAtPtRectCollision(bmp, pt, part, rect) != 0;
}

bool bitmap_part_at_pt_rect_collision_byval(bitmap bmp, const point2d pt, const rectangle part, const rectangle rect)
{
    return sg_Physics_BitmapPartAtPtRectCollision(bmp, &pt, &part, &rect) != 0;
}

bool bitmap_rectangle_collision(bitmap bmp, int32_t x, int32_t y, const rectangle *rect)
{
    return sg_Physics_BitmapRectangleCollision(bmp, x, y, rect) != 0;
}

bool bitmap_rectangle_collision_byval(bitmap bmp, int32_t x, int32_t y, const rectangle rect)
{
    return sg_Physics_BitmapRectangleCollision(bmp, x, y, &rect) != 0;
}

bool bitmap_part_rect_collision(bitmap bmp, int32_t x, int32_t y, const rectangle *part, const rectangle *rect)
{
    return sg_Physics_BitmapPartRectCollision(bmp, x, y, part, rect) != 0;
}

bool bitmap_part_rect_collision_byval(bitmap bmp, int32_t x, int32_t y, const rectangle part, const rectangle rect)
{
    return sg_Physics_BitmapPartRectCollision(bmp, x, y, &part, &rect) != 0;
}

bool bitmap_rect_collision(bitmap bmp, int32_t x, int32_t y, int32_t rectX, int32_t rectY, int32_t rectWidth, int32_t rectHeight)
{
    return sg_Physics_BitmapRectCollision(bmp, x, y, rectX, rectY, rectWidth, rectHeight) != 0;
}

bool cell_bitmap_collision_at_pt(bitmap bmp1, int32_t cell, const point2d *pt1, bitmap bmp2, const point2d *pt2)
{
    return sg_Physics_CellBitmapCollisionAtPt(bmp1, cell, pt1, bmp2, pt2) != 0;
}

bool cell_bitmap_collision_at_pt_byval(bitmap bmp1, int32_t cell, const point2d pt1, bitmap bmp2, const point2d pt2)
{
    return sg_Physics_CellBitmapCollisionAtPt(bmp1, cell, &pt1, bmp2, &pt2) != 0;
}

bool cell_bitmap_part_collision_at_pt(bitmap bmp1, int32_t cell, const point2d *pt1, bitmap bmp2, const point2d *pt2, const rectangle *part)
{
    return sg_Physics_CellBitmapPartCollisionAtPt(bmp1, cell, pt1, bmp2, pt2, part) != 0;
}

bool cell_bitmap_part_collision_at_pt_byval(bitmap bmp1, int32_t cell, const point2d pt1, bitmap bmp2, const point2d pt2, const rectangle part)
{
    return sg_Physics_CellBitmapPartCollisionAtPt(bmp1, cell, &pt1, bmp2, &pt2, &part) != 0;
}

bool cell_bitmap_collision(bitmap bmp1, int32_t cell, int32_t x1, int32_t y1, bitmap bmp2, int32_t x2, int32_t y2)
{
    return sg_Physics_CellBitmapCollision(bmp1, cell, x1, y1, bmp2, x2, y2) != 0;
}

bool cell_bitmap_part_collision(bitmap bmp1, int32_t cell, int32_t x1, int32_t y1, bitmap bmp2, int32_t x2, int32_t y2, const rectangle *part)
{
    return sg_Physics_CellBitmapPartCollision(bmp1, cell, x1, y1, bmp2, x2, y2, part) != 0;
}

bool cell_bitmap_part_collision_byval(bitmap bmp1, int32_t cell, int32_t x1, int32_t y1, bitmap bmp2, int32_t x2, int32_t y2, const rectangle part)
{
    return sg_Physics_CellBitmapPartCollision(bmp1, cell, x1, y1, bmp2, x2, y2, &part) != 0;
}

bool cell_collision_at_pt(bitmap bmp1, int32_t cell1, const point2d *pt1, bitmap bmp2, int32_t cell2, const point2d *pt2)
{
    return sg_Physics_CellCollisionAtPt(bmp1, cell1, pt1, bmp2, cell2, pt2) != 0;
}

bool cell_collision_at_pt_byval(bitmap bmp1, int32_t cell1, const point2d pt1, bitmap bmp2, int32_t cell2, const point2d pt2)
{
    return sg_Physics_CellCollisionAtPt(bmp1, cell1, &pt1, bmp2, cell2, &pt2) != 0;
}

bool cell_collision(bitmap bmp1, int32_t cell1, int32_t x1, int32_t y1, bitmap bmp2, int32_t cell2, int32_t x2, int32_t y2)
{
    return sg_Physics_CellCollision(bmp1, cell1, x1, y1, bmp2, cell2, x2, y2) != 0;
}

bool cell_rect_collision_at_pt(bitmap bmp, int32_t cell, const point2d *pt, const rectangle *rect)
{
    return sg_Physics_CellRectCollisionAtPt(bmp, cell, pt, rect) != 0;
}

bool cell_rect_collision_at_pt_byval(bitmap bmp, int32_t cell, const point2d pt, const rectangle rect)
{
    return sg_Physics_CellRectCollisionAtPt(bmp, cell, &pt, &rect) != 0;
}

bool cell_rect_collision(bitmap bmp, int32_t cell, int32_t x, int32_t y, const rectangle *rect)
{
    return sg_Physics_CellRectCollision(bmp, cell, x, y, rect) != 0;
}

bool cell_rect_collision_byval(bitmap bmp, int32_t cell, int32_t x, int32_t y, const rectangle rect)
{
    return sg_Physics_CellRectCollision(bmp, cell, x, y, &rect) != 0;
}

bool circle_circle_collision(const circle *c1, const circle *c2)
{
    return sg_Physics_CircleCircleCollision(c1, c2) != 0;
}

bool circle_circle_collision_byval(const circle c1, const circle c2)
{
    return sg_Physics_CircleCircleCollision(&c1, &c2) != 0;
}

bool sprite_circle_line_collision(sprite s, const line_segment *line)
{
    return sg_Physics_SpriteCircleLineCollision(s, line) != 0;
}

bool sprite_circle_line_collision_byval(sprite s, const line_segment line)
{
    return sg_Physics_SpriteCircleLineCollision(s, &line) != 0;
}

bool circle_lines_collision(const circle *c, const lines_array lines, int32_t lines_len)
{
    return sg_Physics_CircleLinesCollision(c, lines, lines_len) != 0;
}

bool circle_lines_collision_byval(const circle c, const lines_array lines, int32_t lines_len)
{
    return sg_Physics_CircleLinesCollision(&c, lines, lines_len) != 0;
}

bool circle_rect_collision(const circle *c, const rectangle *rect)
{
    return sg_Physics_CircleRectCollision(c, rect) != 0;
}

bool circle_rect_collision_byval(const circle c, const rectangle rect)
{
    return sg_Physics_CircleRectCollision(&c, &rect) != 0;
}

bool circle_triangle_collision(const circle *c, const triangle tri)
{
    return sg_Physics_CircleTriangleCollision(c, tri) != 0;
}

bool circle_triangle_collision_byval(const circle c, const triangle tri)
{
    return sg_Physics_CircleTriangleCollision(&c, tri) != 0;
}

void collide_circle_circle(sprite s, const circle *c)
{
    sg_Physics_CollideCircleCircle(s, c);
}

void collide_circle_circle_byval(sprite s, const circle c)
{
    sg_Physics_CollideCircleCircle(s, &c);
}

void collide_circle_line(sprite s, const line_segment *line)
{
    sg_Physics_CollideCircleLine(s, line);
}

void collide_circle_line_byval(sprite s, const line_segment line)
{
    sg_Physics_CollideCircleLine(s, &line);
}

void collide_circle_lines(sprite s, const lines_array lines, int32_t lines_len)
{
    sg_Physics_CollideCircleLines(s, lines, lines_len);
}

void collide_circle_lines_byval(sprite s, const lines_array lines, int32_t lines_len)
{
    sg_Physics_CollideCircleLines(s, lines, lines_len);
}

void collide_circle_rectangle(sprite s, const rectangle *rect)
{
    sg_Physics_CollideCircleRectangle(s, rect);
}

void collide_circle_rectangle_byval(sprite s, const rectangle rect)
{
    sg_Physics_CollideCircleRectangle(s, &rect);
}

void collide_circles(sprite s1, sprite s2)
{
    sg_Physics_CollideCircles(s1, s2);
}

bool sprite_rect_line_collision(sprite s, const line_segment *line)
{
    return sg_Physics_SpriteRectLineCollision(s, line) != 0;
}

bool sprite_rect_line_collision_byval(sprite s, const line_segment line)
{
    return sg_Physics_SpriteRectLineCollision(s, &line) != 0;
}

bool rect_line_collision(const rectangle *rect, const line_segment *line)
{
    return sg_Physics_RectLineCollision(rect, line) != 0;
}

bool rect_line_collision_byval(const rectangle rect, const line_segment line)
{
    return sg_Physics_RectLineCollision(&rect, &line) != 0;
}

collision_side side_for_collision_test(const vector *velocity)
{
    return sg_Physics_SideForCollisionTest(velocity);
}

collision_side side_for_collision_test_byval(const vector velocity)
{
    return sg_Physics_SideForCollisionTest(&velocity);
}

bool sprite_bitmap_at_point_collision(sprite s, bitmap bmp, const point2d *pt)
{
    return sg_Physics_SpriteBitmapAtPointCollision(s, bmp, pt) != 0;
}

bool sprite_bitmap_at_point_collision_byval(sprite s, bitmap bmp, const point2d pt)
{
    return sg_Physics_SpriteBitmapAtPointCollision(s, bmp, &pt) != 0;
}

bool sprite_bitmap_collision(sprite s, bitmap bmp, float x, float y)
{
    return sg_Physics_SpriteBitmapCollision(s, bmp, x, y) != 0;
}

bool sprite_collision(sprite s1, sprite s2)
{
    return sg_Physics_SpriteCollision(s1, s2) != 0;
}

bool sprite_rectangle_collision(sprite s, const rectangle *r)
{
    return sg_Physics_SpriteRectangleCollision(s, r) != 0;
}

bool sprite_rectangle_collision_byval(sprite s, const rectangle r)
{
    return sg_Physics_SpriteRectangleCollision(s, &r) != 0;
}

bool sprite_rect_collision(sprite s, float x, float y, int32_t width, int32_t height)
{
    return sg_Physics_SpriteRectCollision(s, x, y, width, height) != 0;
}

bool triangle_line_collision(const triangle tri, const line_segment *ln)
{
    return sg_Physics_TriangleLineCollision(tri, ln) != 0;
}

bool triangle_line_collision_byval(const triangle tri, const line_segment ln)
{
    return sg_Physics_TriangleLineCollision(tri, &ln) != 0;
}

