/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - SGSDK
*
* Wrapping SGSDK.pas
*/

#include "SGSDK.h"
#include "SGSDK.h"

#include "Timers.h"
#include "Physics.h"
#include "Characters.h"
#include "Audio.h"
#include "Images.h"
#include "Animations.h"
#include "Utils.h"
#include "Input.h"
#include "Types.h"
#include "Graphics.h"
#include "Geometry.h"
#include "Text.h"
#include "Resources.h"
#include "Camera.h"
#include "Sprites.h"

